apiVersion: v1
kind: Service
metadata:
  name: fastapi-helloworld
  namespace: demo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  selector:
    app: fastapi-helloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-helloworld
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-helloworld
  template:
    metadata:
      labels:
        app: fastapi-helloworld
    spec:
      containers:
      - name: kubernetes-fastapi-helloworld
        image: ehsanullahkhan/fastapi-helloworld
        ports:
        - containerPort: 80

