version: "3.8"

services:
  fast-helloworld:
    build: .
    image: 'fastapi-helloworld:1.0'
    command: bash -c 'uvicorn main:app --host 0.0.0.0 --port 8000'
    volumes:
      - .:/app
    ports:
      - 8000:8000
